### ISSUE TITLE
Menu dosent open, i installed cleo

### ISSUE THREAD

**Issue by aswertyStuff** [user-grinch/CheatMenuBullySC#1]
Was i not supossed to use the .exe file or was it manualy, or was i supossed to not select anything, please help

**Comment by aswertyStuff** [comment]
or do i have to install an asi loader separrataly

**Comment by user-grinch** [comment]
The CLEO Redux installer should install everything needed. Then just drag & drop the files into CLEO folder.

**Comment by aswertyStuff** [comment]
Is it version spesific

**Comment by aswertyStuff** [comment]
cause it dosent work

**Comment by user-grinch** [comment]
Yes, you need Bully v1.0

**Comment by aswertyStuff** [comment]
i have 1.200 is there a way to downgrade it or am i doing something wrong, here are some pictures
![ragatanga](https://github.com/user-grinch/CheatMenuBullySC/assets/112781526/37147149-8d50-4497-b073-ccfa014b8432)
![wah](https://github.com/user-grinch/CheatMenuBullySC/assets/112781526/63b69fe4-da51-4754-945e-5bf105c6ff94)
